# Data
For our research project, we choose to use Global Historical Climatology Network (GHCN)-Daily Dataset. It is a composite dataset comprising climate records from numerous sources worldwide. These records are merged and subjected to quality assurance reviews. The dataset is maintained by the National Oceanic and Atmospheric Administration (NOAA). 

The data we get from NOAA data source is in csv format. The data is distributed typically with one row per observation, indicating one observation per day. We choose to use the date range between 2023-01-01 to 2023-11-27 for analysis of the most current trend in atmosphere. Updates of the dataset are made in either several days or a week, ensuring a near-real-time data feed. 

For the coverage of the dataset, it includes over 40 meteorological elements such as temperature extremes, precipitation, wind speed, and direction. Within our choice of range, it includes 312 stations for observations, which allows for later analysis on geographical comparisons. 

Potential issues might include varying data quality and completeness across stations and time periods. For our purpose of research, there does exist some missing data in some of the targeted columns, and therefore needs further filtering and processes to deal with. 

For importing data, we choose to import the csv file we got from the NOAA source into R using standard data reading functions like read.csv(). 


Data Link: https://www.ncei.noaa.gov/cdo-web/datasets/GHCND/locations/CITY:US360019/detail

## Description

## Missing value analysis
